Update init.ps1
Missing comma in line #43 which causing the ParserError issue while running the .\init.ps1.

ParserError: D:\Playground\XM-Cloud-Introduction\init.ps1:43
Line |
  43 |      [string]$SUCGON_NA_CDP_POINTOFSALE
     |                                        ~
     | Missing ')' in function parameter list.